@startuml

(*) --> [Начало] "Аутентификация"
note left: Запрос MessageUser

if "Сессия новая?" then
    --> [Да] "Новая сессия"
    --> "Страница авторизации"
    --> === End === 
else
    -right-> [Нет] "Есть информация о сесии"
    if "Пользователь авторизован?" then
        --> [Да] "Достать информацию о пользователе"
        -right-> "Отправить информацию клиенту"
    else
        -right-> [Нет] "Достать информацию о местонахождении"
        --> "Отправить информацию клиенту"
        --> === End === 
    endif
endif

=== End === --> [Конец](*)

@enduml